sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
env:
    - IS_OFFLINE=true
before_install:
    - docker pull carlad/sinatra
    - npm install -g yarn
install:
    - yarn
script:
    - npm run lint
    - npm run test