sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
before_install:
    - docker pull lambci/lambda
    - docker pull lambci/lambda:nodejs4.3
    - docker pull lambci/lambda:python2.7
    - npm install -g yarn
install:
    - yarn
script:
    - yarn run lint
    - yarn run test -- --coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
