sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
env:
    - IS_OFFLINE=true
before_install:
    - docker pull lambci/lambda
    - npm install -g yarn
install:
    - yarn
script:
    - npm run lint
    - npm run test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage