service: docker

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1

plugins:
  - serverless-docker

functions:
  authorizer:
    handler: functions/authorizer.handler
    type: 'TOKEN'
    identitySource: method.request.header.Authorization

  bffHandler:
    handler: functions/bff.handler
    environment:
      BFF_BACKEND_FUNC: ${self:service}-${opt:stage, self:provider.stage}-bffBackend
    events:
      - http:
          path: bff
          method: GET

  bffBackend:
    handler: functions/bff.backend

  error:
    handler: functions/lambda-proxy.unhandled
    events:
      - http:
          path: error
          method: GET

  lists:
    handler: functions/lambda-proxy.success
    events:
      - http:
          path: lists
          method: GET
          authorizer:
            name: authorizer
            type: 'TOKEN'
            identitySource: method.request.header.Authorization
      - http:
          path: lists
          method: POST
          authorizer: authorizer
      - http:
          path: lists
          method: PUT

  currentTime:
    handler: functions/handler.endpoint
    runtime: python2.7
    events:
      - http:
          path: ping
          method: get

  timeout:
    handler: functions/timeout.handler
    timeout: 1
    memorySize: 128
